JWT_TOKEN="never-gonna-run-around-and-desert-you"
OPENAI_API_KEY="never-gonna-give-you-up"
GOOGLE_API_KEY="AIzaSyD_JLKOilNJCgManxHe9LCnu175W_74p7s"
JWT_SECRET_KEY="never-gonna-run-around-and-desert-you"
MONGODB_URI = "mongodb://127.0.0.1:27017/"
